# Generated by Django 2.2.4 on 2019-09-09 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0011_profile_customer_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subscriptions', '0003_subscriptions_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.CharField(blank=True, max_length=70, unique=True)),
                ('active', models.BooleanField(blank=True)),
                ('amount', models.BigIntegerField(blank=True)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('name', models.CharField(blank=True, max_length=20, unique=True)),
                ('product', models.CharField(blank=True, max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('status', models.CharField(blank=True, max_length=10)),
                ('plan_id', models.CharField(blank=True, max_length=70)),
                ('account', models.ForeignKey(on_delete=None, to='account.Account')),
                ('subscription', models.ForeignKey(on_delete=None, to='subscriptions.Subscriptions')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
