# Generated by Django 2.2.4 on 2019-08-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='card_number',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='account',
            name='expiry',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='scv',
            field=models.CharField(max_length=10),
        ),
    ]
