# Generated by Django 2.2.4 on 2019-09-03 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20190828_0658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='scv',
            new_name='cvc',
        ),
    ]
