# Generated by Django 2.2.4 on 2019-09-03 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20190903_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='cvc',
            field=models.CharField(max_length=3),
        ),
        migrations.AlterField(
            model_name='account',
            name='expiry',
            field=models.CharField(max_length=10),
        ),
    ]
