# Generated by Django 2.2.4 on 2019-09-08 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='stripe_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='title',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
