# Generated by Django 2.2.4 on 2019-09-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_auto_20190909_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='brand',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='account',
            name='last4',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='account',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
