# Generated by Django 2.2.4 on 2019-09-09 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20190909_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='price',
            field=models.BigIntegerField(default=0),
        ),
    ]
